{% set name = "bgcArgoDMQC" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bgcArgoDMQC-{{ version }}.tar.gz
  sha256: 18a7a5ad406e5739e7a5cbc634388a0360b28bbd4ecdd7f9d311c074770c9047

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - cmocean
    - gsw
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - python >=3.4
    - scipy
    - seaborn

test:
  imports:
    - bgcArgoDMQC
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ArgoCanada/bgcArgoDMQC
  summary: A python library for quality control of BGC-Argo data
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - cgrdn
